language: julia
julia:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  
#script:
#    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#    - julia -e 'Pkg.clone(pwd()); Pkg.test("ChebyshevApprox", coverage=true)'
after_success:
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("ChebyshevApprox")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
